version: '3'
services:
  client:
    image: 'ghcr.io/cyator/N2-Avionics-BaseStation:0.1.0-alpha'
    restart: always
    ports:
      - 3000:3000
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - "1883:1883"   
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log  
    restart: always

  influxdb:
    image: influxdb:2.3-alpine
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      # Use these same configurations parameters in your telegraf configuration, telegraf.conf.
      - ./.env.local
    #entrypoint: ["./entrypoint.sh"]
    #restart: on-failure:10
    #depends_on:
    #  - influxdb
    restart: always
  telegraf:
    image: telegraf:1.20-alpine
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    env_file: 
      - ./.env.local
    depends_on:
      - mosquitto
      - influxdb_cli
      - client
    restart: always
  
volumes:
  influxdb2:
  mosquitto-data:
  mosquitto-log:
